### ISSUE TITLE
UI and working process are synchronous

### ISSUE THREAD

**Issue by tajnymag** [Fr0sT-Brutal/App_EXIFTimeEdit#5]
Any larger amount of photos wil freeze the app as it seems the timestamp-changing job is being run in the main thread.

**Comment by Fr0sT-Brutal** [comment]
Sorry for slowpoke response :)
This app doesn't need to be responsible while doing job. Nevertheless I made ProcessMessages to happen each 1 sec instead of each 10 files (for very slow processings). I tried with 1000 photos on a flash drive and app changed them all in 1-2 sec.
